project_id = "qrujvdsmwgccxkgjznvx"

[functions.sync-sheets-employees]
verify_jwt = false

[functions.sync-sheets-stores]
verify_jwt = true

[functions.check-sheets-consistency]
verify_jwt = true

[functions.manage-user-auth]
verify_jwt = true
