/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedTurnosRouteImport } from './routes/_authenticated/turnos'
import { Route as AuthenticatedRegionalRouteImport } from './routes/_authenticated/regional'
import { Route as AuthenticatedHorasRouteImport } from './routes/_authenticated/horas'
import { Route as AuthenticatedEscalasRouteImport } from './routes/_authenticated/escalas'
import { Route as AuthenticatedConfigLojaRouteImport } from './routes/_authenticated/config-loja'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedAlteracoesRouteImport } from './routes/_authenticated/alteracoes'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurnosRoute = AuthenticatedTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegionalRoute = AuthenticatedRegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorasRoute = AuthenticatedHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalasRoute = AuthenticatedEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigLojaRoute = AuthenticatedConfigLojaRouteImport.update({
  id: '/config-loja',
  path: '/config-loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlteracoesRoute = AuthenticatedAlteracoesRouteImport.update({
  id: '/alteracoes',
  path: '/alteracoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alteracoes': typeof AuthenticatedAlteracoesRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/config-loja': typeof AuthenticatedConfigLojaRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/horas': typeof AuthenticatedHorasRoute
  '/regional': typeof AuthenticatedRegionalRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alteracoes': typeof AuthenticatedAlteracoesRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/config-loja': typeof AuthenticatedConfigLojaRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/horas': typeof AuthenticatedHorasRoute
  '/regional': typeof AuthenticatedRegionalRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/alteracoes': typeof AuthenticatedAlteracoesRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/config-loja': typeof AuthenticatedConfigLojaRoute
  '/_authenticated/escalas': typeof AuthenticatedEscalasRoute
  '/_authenticated/horas': typeof AuthenticatedHorasRoute
  '/_authenticated/regional': typeof AuthenticatedRegionalRoute
  '/_authenticated/turnos': typeof AuthenticatedTurnosRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alteracoes'
    | '/cadastros'
    | '/config-loja'
    | '/escalas'
    | '/horas'
    | '/regional'
    | '/turnos'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alteracoes'
    | '/cadastros'
    | '/config-loja'
    | '/escalas'
    | '/horas'
    | '/regional'
    | '/turnos'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/alteracoes'
    | '/_authenticated/cadastros'
    | '/_authenticated/config-loja'
    | '/_authenticated/escalas'
    | '/_authenticated/horas'
    | '/_authenticated/regional'
    | '/_authenticated/turnos'
    | '/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turnos': {
      id: '/_authenticated/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof AuthenticatedTurnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regional': {
      id: '/_authenticated/regional'
      path: '/regional'
      fullPath: '/regional'
      preLoaderRoute: typeof AuthenticatedRegionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas': {
      id: '/_authenticated/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof AuthenticatedHorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escalas': {
      id: '/_authenticated/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AuthenticatedEscalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config-loja': {
      id: '/_authenticated/config-loja'
      path: '/config-loja'
      fullPath: '/config-loja'
      preLoaderRoute: typeof AuthenticatedConfigLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alteracoes': {
      id: '/_authenticated/alteracoes'
      path: '/alteracoes'
      fullPath: '/alteracoes'
      preLoaderRoute: typeof AuthenticatedAlteracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlteracoesRoute: typeof AuthenticatedAlteracoesRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedConfigLojaRoute: typeof AuthenticatedConfigLojaRoute
  AuthenticatedEscalasRoute: typeof AuthenticatedEscalasRoute
  AuthenticatedHorasRoute: typeof AuthenticatedHorasRoute
  AuthenticatedRegionalRoute: typeof AuthenticatedRegionalRoute
  AuthenticatedTurnosRoute: typeof AuthenticatedTurnosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlteracoesRoute: AuthenticatedAlteracoesRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedConfigLojaRoute: AuthenticatedConfigLojaRoute,
  AuthenticatedEscalasRoute: AuthenticatedEscalasRoute,
  AuthenticatedHorasRoute: AuthenticatedHorasRoute,
  AuthenticatedRegionalRoute: AuthenticatedRegionalRoute,
  AuthenticatedTurnosRoute: AuthenticatedTurnosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
